name: Metrics
on:
  schedule:
    - cron: "0 0 * * *" # Daily
  workflow_dispatch:
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: AniList
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.anilist.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: LKDI
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 1

          output_action: commit
          committer_branch: metrics
          committer_message: "update AniList metrics [skip ci]"

      - name: WakaTime
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.wakatime.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, languages, languages-graphs
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}

          output_action: commit
          committer_branch: metrics
          committer_message: "update WakaTime metrics [skip ci]"

      - name: Last.fm
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_music_token: ${{ secrets.LASTFM_API_KEY }}
          plugin_music: yes
          plugin_music_provider: lastfm
          plugin_music_user: RJ

          output_action: commit
          committer_branch: metrics
          committer_message: "update Last.fm metrics [skip ci]"


