name: Generate snake animation

on:
  schedule:
    - cron: "0 0 * * *" # Daily
  # Allows to manually run the job at any time
  workflow_dispatch:
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Snake in contribution grid
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/light.svg?palette=github-light
            dist/dark.svg?palette=github-dark

      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file>
      - name: Push images to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: snake
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
