name: WakaTime status update

on:
  schedule:
    - cron: "0 */24 * * *"  # 24 Hours
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - name: Initializing Waka key
        run: echo "Initializing key ${{ secrets.WAKATIME_API_KEY }}"
      - uses: avinal/Profile-Readme-WakaTime@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
          # Branch - newer GitHub repositories have "main" as default branch, change to main in that case, default is master
          BRANCH: waka
          COMMIT_MSG: "Update WakaTime stats"
          # Range of fetching data - default is "last_7_days". See https://wakatime.com/developers#stats for more options
          STATS_RANGE: last_30_days
